### ISSUE TITLE
Add list of projects that use specta to readme

### ISSUE THREAD

**Issue by mickeyreiss** [specta/specta#140]
It seems to me like one of the goals in #125 is to keep specta alive and stable in the post-objective-c-yet-somehow-pre-swift world. When people feel confident in a library, they're more likely to use it; and when more people use it, some might contribute back to it.

Do others agree that adding a list of projects that use specta in production would lend some legitimacy to the project once it hits 1.0?

**Comment by orta** [comment]
I think Specta has semi-accidentally become one of the most widespread testing framework due to it being the default when creating [a new CocoaPod](http://guides.cocoapods.org/making/using-pod-lib-create.html).

My initial worry was a lack of releases and a sense of stagnation, that I feel is gone. I think this makes sense for a wiki page though!

**Comment by orta** [comment]
OK, I'm calling this one as not needed, there's at least [4,000 test targets](http://cocoapods.org/pods/Specta) using Specta now 👯
