### ISSUE TITLE
helper functions?

### ISSUE THREAD

**Issue by pvinis** [specta/specta#171]
hi. is it possible to have a couple of methods like `- (void)bla {}` or `void foo()` in a test file, so that in an `it` block, i can call those helper methods?

**Comment by orta** [comment]
If you put it outside the `SpecBegin` and `SpecEnd` blocks then you can treat it like any objective-c file, including [methods](https://github.com/artsy/eigen/blob/master/Artsy_Tests/Networking_Tests/Collection/ARGeneArtworksNetworkModelTests.m#L98), [classes](https://github.com/artsy/eigen/blob/master/Artsy_Tests/Networking_Tests/Collection/ARGeneArtworksNetworkModelTests.m#L4-L11) etc.

**Comment by pvinis** [comment]
thanks

**Comment by ooopscc** [comment]
Hello,
What if I want to repeat a logic code several times, instead of write it many times, how can I create a block or function to still use `expect()`?
I notice it always failed if I create a block put in anywhere between `SpecBegin` and `SpecEnd`, and it will run test twice, that's wired.
for example
```
void (^routine)(NSArray *) = ^(NSArray *array) {
    expect(array.count).beGreaterThan(0);
    expect([array.firstObject isKindOfClass:[NSData class]]).beTruthy();
    expect(array.lastObject).equal(@"233");
    ...
}

where should I put it in?
