### ISSUE TITLE
`fit` within `fdescribe` still runs all `it` blocks in the spec

### ISSUE THREAD

**Issue by sebastiangrail** [specta/specta#173]
If I nest a `fit` in an `fdescribe`, I expect that _only_ the `fit` runs. Instead, all tests in the `fdescribe` block run.

``` objc
fdescribe(@"foo", ^{
    it(@"shouldn't run this test", ^{
        ...
    }
    fit(@"should only run this test", ^{
        ...
    }
}
```

**Comment by orta** [comment]
This makes sense, would happily accept PRs on this :+1:

**Comment by evilDave** [comment]
This does not make a whole lot of sense to me. It makes focusing an outer block meaningless. I find that the current behaviour, that focusing an outer block takes precedence over any focusing of contained blocks, is correct.

Under your suggested interpretation, what is the difference then between these:

```
fdescribe(@"foo", ^{
    it(@"should bar", ^{
        ...
    }
    fit(@"should baz", ^{
        ...
    }
}
```

```
describe(@"foo", ^{
    it(@"should bar", ^{
        ...
    }
    fit(@"should baz", ^{
        ...
    }
}
```

does this not create two ways to specify the same behaviour?

What should this do?:

```
fdescribe(@"foo", ^{
    it(@"should bar", ^{
        ...
    }
    it(@"should baz", ^{
        ...
    }
}
```

nothing? Or the focus the whole describe block?

Lastly, what would you do to get all the contents of a block to focus? (focus all of the inner blocks individually?)

This change would add no additional behaviour, and actually remove (make more verbose) a behaviour that is currently possible. Incidentally, in order to "run only the fit" all you need to do is to specify only the fit (not the fdescribe)... was your workflow first to focus on the describe then narrow down to the it block? If so I can see how you got there, but all you need do is remove the fdescribe and add the fit(s).

(I'm sorry that my first contribution here could be seen as purely negative, but no-one else seemed to be making this point and I can't see how this change would be an improvement, quite the opposite.)

Thanks.
