### ISSUE TITLE
Shared behavior: 'it' clause does not work properly

### ISSUE THREAD

**Issue by bwaresiak** [specta/specta#94]
Hello, 

With Specta 0.2.1, I'm using such shared behavior:

    sharedExamplesFor(@"shared example", ^(NSDictionary* data)
    {
        NSString *something = data[SBEventKey];
    
        it(@"should work", ^{
            expect(something).toNot.beNil();
            expect(something).to.equal(@"something");
        });
    });

When I pass parameter which does not meet the required criteria to the dictionary, test still passes, even tho I'm expecting it to fail. The block within 'it' is never processed.

Changing to:

    sharedExamplesFor(@"shared example", ^(NSDictionary* data)
    {
        NSString *something = data[SBEventKey];
    
        expect(something).toNot.beNil();
        expect(something).to.equal(@"something");
    });

Works as expected - tests are failing.

Can someone verify this? Am I doing something wrong? Is it not legal to use 'it' within shared behavior? 

Thanks

**Comment by paweldudek** [comment]
@bwaresiak the problem here is that you're not using `it` and `beforeEach` blocks in `sharedExamplesFor`. Under the hood they behave just like a describe block (which can be passed some additional info). 

Thus the appropriate approach would be:

```
sharedExamplesFor(@"shared example", ^(NSDictionary* data)
{
    beforeEach(^{
        NSString *something = data[SBEventKey];
    });

    it(@"should work", ^{
        expect(something).toNot.beNil();
        expect(something).to.equal(@"something");
    });
});
```

And it is absolutely legal (actually required) to use `it` with shared behaviours. The fact that your tests were passing in the first place is probably because you passed in a simple dictionary to your `itShouldBehaveLike` rather than a block that generates a dict, tho I'm not 100% sure about this. 

@orta this probably means a better documentation on shared examples is needed, there were two issues where people reported problems with using them. (other issue: https://github.com/specta/specta/issues/103)

**Comment by paweldudek** [comment]
Nvm, I see this was already fixed in https://github.com/specta/specta/commit/93c65aee31bfcbe439da58a1e180069de07f9c64, awesome!

**Comment by orta** [comment]
Agree, documentation issue.
